CREATE TABLE promo_codes(
	id CHAR(5) NOT NULL,
	eventID INTEGER UNSIGNED NOT NULL,
	type DECIMAL(3,2) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	PRIMARY KEY (id, eventID),
	FOREIGN KEY(eventID) REFERENCES events(id)
);