CREATE TABLE SUBSCRIBE(
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	categoryID INTEGER UNSIGNED NOT NULL,
	userID INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(created_at,categoryID, userID),
	FOREIGN KEY (categoryID) REFERENCES categories(id),
	FOREIGN KEY (userID) REFERENCES users(id)
);